title: Leonaries's Blog
description: Welcome to my personal blog
baseurl: "" # 对于用户站点，这里应该为空
url: "https://leonaries.github.io"
theme: minima # 使用 GitHub Pages 支持的默认主题

# 基本设置
markdown: kramdown
permalink: /:year/:month/:day/:title/

# 作者信息
author:
  name: Leonaries