name: Deploy GitHub Pages

on:
  push:
    branches:
      - master  # 或者 main，取决于您的默认分支名称
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build VuePress site
        run: npm run docs:build
        
      - name: Copy CNAME
        run: cp docs/.vuepress/public/CNAME docs/.vuepress/dist/
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/.vuepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2